export const data = [
	{
		id: 1,
		Title: "Gitanjali",
		Subject: "Novel",
		Author: "Rabindranath Tagore",
		Publish_Date: "4th August,1910",
	},
	{
		id: 2,
		Title: "Shesher Kabita",
		Subject: "Novel",
		Author: "Rabindranath Tagore",
		Publish_Date: "10th January,1928",
	},
	{
		id: 3,
		Title: "Nineteen Eighty-Four",
		Subject: "Novel",
		Author: "George Orwell",
		Publish_Date: "3rd December,1949",
	},
	{
		id: 4,
		Title: "Harry Potter",
		Subject: "Novel",
		Author: "J.K. Rowling",
		Publish_Date: "23rd January ,1997",
	},
	{
		id: 5,
		Title: "Pursuit of happiness",
		Subject: "Novel",
		Author: "Douglas Kennedy ",
		Publish_Date: "2nd September,2001",
	},
	{
		id: 6,
		Title: "The English Teacher",
		Subject: "Novel",
		Author: "RK Narayan",
		Publish_Date: "3rd June,1995",
	},
	{
		id: 7,
		Title: "The Secret Garden",
		Subject: "Novel",
		Author: "E.F Benson",
		Publish_Date: "8th February,1943",
	},
	{
		id: 8,
		Title: "One Indian Girl",
		Subject: "Novel",
		Author: "Chetan Bhagat",
		Publish_Date: "1st October,2016",
	},
	{
		id: 9,
		Title: "The Guide",
		Subject: "Novel",
		Author: "RK Narayan",
		Publish_Date: "12th April,1958",
	},
	{
		id: 10,
		Title: "The Three Mistakes Of My Life",
		Subject: "Novel",
		Author: "Chetan Bhagat",
		Publish_Date: "1st January,2008",
	},
	{
		id: 11,
		Title: "The Merchant Of Venice",
		Subject: "Drama",
		Author: "William Shakespeare",
		Publish_Date: "written in 1596",
	},
	{
		id: 12,
		Title: "Romeo and Juliet",
		Subject: "Drama",
		Author: "William Shakespeare",
		Publish_Date: "written in 1594",
	},
	{
		id: 13,
		Title: "Hamlet",
		Subject: "Drama",
		Author: "William Shakespeare",
		Publish_Date: "written in 1600",
	},
	{
		id: 14,
		Title: "Kaumudi",
		Subject: "Drama",
		Author: "Abhishek Majumdar",
		Publish_Date: "written in 1980",
	},
	{
		id: 15,
		Title: "Shakuntala",
		Subject: "Drama",
		Author: "Kalidasa",
		Publish_Date: "written in 2017",
	},
	{
		id: 16,
		Title: "Valmiki Pratibha",
		Subject: "Drama",
		Author: "Rabindranath Tagore",
		Publish_Date: "written in 1881",
	},
	{
		id: 17,
		Title: "Andher Nagari",
		Subject: "Drama",
		Author: "Bharatendu Harischandra",
		Publish_Date: "written in 1881",
	},
	{
		id: 18,
		Title: "Home, I am Darling",
		Subject: "Drama",
		Author: "Laura Wade",
		Publish_Date: "written in 2018",
	},
	{
		id: 19,
		Title: "Othello",
		Subject: "Drama",
		Author: "William Shakespeare",
		Publish_Date: "written in 1604",
	},
	{
		id: 20,
		Title: "Julius Caesar",
		Subject: "Drama",
		Author: "William Shakespeare",
		Publish_Date: "written in 1599",
	},
	{
		id: 21,
		Title: "In the Bazaars of Hyderabad",
		Subject: "Poem",
		Author: "Sarojini Naidu",
		Publish_Date: "1912",
	},
	{
		id: 22,
		Title: "Sonnet 18",
		Subject: "Poem",
		Author: "William Shakespeare",
		Publish_Date: "1609",
	},
	{
		id: 23,
		Title: "The Road Not Taken",
		Subject: "Poem",
		Author: "Robert Frost",
		Publish_Date: "1916",
	},
	{
		id: 24,
		Title: "Stopping By Woods",
		Subject: "Poem",
		Author: "Robert Frost",
		Publish_Date: "1922",
	},
	{
		id: 25,
		Title: "Ramcharitmanas",
		Subject: "Poem",
		Author: "Tulsidas",
		Publish_Date: "1633",
	},
	{
		id: 26,
		Title: "Koyel",
		Subject: "Poem",
		Author: "Mahadevi Verma",
		Publish_Date: "1899",
	},
	{
		id: 27,
		Title: "Madhubala",
		Subject: "Poem",
		Author: "Harivansh Rai Bacchan",
		Publish_Date: "1936",
	},
	{
		id: 28,
		Title: "Prelude",
		Subject: "Poem",
		Author: "William Wordsworth",
		Publish_Date: "1798",
	},
	{
		id: 29,
		Title: "Vande Mataram",
		Subject: "Poem",
		Author: "Bankim Chandra Chatterjee",
		Publish_Date: "1882",
	},
	{
		id: 30,
		Title: "Meghaduta",
		Subject: "Poem",
		Author: "Kalidasa",
		Publish_Date: "1952",
	},
	{
		id: 31,
		Title: "Ramayana",
		Subject: "Religious",
		Author: "Valmiki",
		Publish_Date: "700BCE-300CE",
	},
	{
		id: 32,
		Title: "The Secret of Nagas",
		Subject: "Religious",
		Author: "Amish Tripathi",
		Publish_Date: "2011",
	},
	{
		id: 33,
		Title: "The Immortals of Meluha",
		Subject: "Religious",
		Author: "Amish Tripathi",
		Publish_Date: "2010",
	},
	{
		id: 34,
		Title: "The Oath of Vayuputras",
		Subject: "Religious",
		Author: "Amish Tripathi",
		Publish_Date: "2013",
	},
	{
		id: 35,
		Title: "My Gita",
		Subject: "Religious",
		Author: "Devdutt Pattanaik",
		Publish_Date: "2015",
	},
	{
		id: 36,
		Title: "Gurus",
		Subject: "Religious",
		Author: "Bhavdeep Kang",
		Publish_Date: "2016",
	},
	{
		id: 37,
		Title: "Triptakas",
		Subject: "Religious",
		Author: "Mahakashyapa",
		Publish_Date: "1st Century CE",
	},
	{
		id: 38,
		Title: "Yoga Mythology",
		Subject: "Religious",
		Author: "Devdutt Pattanaik",
		Publish_Date: "2019",
	},
	{
		id: 39,
		Title: "The Jaina Path Of Purification",
		Subject: "Religious",
		Author: "Padmanabh Jaini",
		Publish_Date: "1979",
	},
	{
		id: 40,
		Title: "The Last Avtaar(Age of Kalki #1)",
		Subject: "Religious",
		Author: "Vishwas Mudagal",
		Publish_Date: "2018",
	},
	{
		id: 41,
		Title: "Autobiography of a Yogi",
		Subject: "Biography",
		Author: "Paramhansa Yogananda ",
		Publish_Date: "1946",
	},
	{
		id: 42,
		Title: "Einstein: His Life and Universe",
		Subject: "Biography",
		Author: "Walter Issascon",
		Publish_Date: "2007",
	},
	{
		id: 43,
		Title: "The Test of My Life",
		Subject: "Biography",
		Author: "Yuvraj Singh",
		Publish_Date: "2013",
	},
	{
		id: 44,
		Title: "Race Of My Life",
		Subject: "Biography",
		Author: "Milkha Singh",
		Publish_Date: "2013",
	},
	{
		id: 45,
		Title: "The Wings Of Fire",
		Subject: "Biography",
		Author: "A.P.J. Abdul Kalam",
		Publish_Date: "1999",
	},
	{
		id: 46,
		Title: "Cleopatra:A Life",
		Subject: "Biography",
		Author: "Stacy Schiff",
		Publish_Date: "2010",
	},
	{
		id: 47,
		Title: "Leonardo da Vinchi",
		Subject: "Biography",
		Author: "Walter Issascon",
		Publish_Date: "2017",
	},
	{
		id: 48,
		Title: "A long walk to freedom",
		Subject: "Biography",
		Author: "Nelson Mandala",
		Publish_Date: "1994",
	},
	{
		id: 49,
		Title: "Becoming",
		Subject: "Biography",
		Author: "Michelle Obama",
		Publish_Date: "2018",
	},
	{
		id: 50,
		Title: "Elon Musk",
		Subject: "Biography",
		Author: "Ashlee Vance",
		Publish_Date: "2015",
	}
];
